### ISSUE TITLE
Find a Rust or C speech-to-text library

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#12]
If the size of the library allows - it would be nice to have a speech-to-text library. It will probably be a language dependent download. We don't want to download all languages - but maybe there's one that can be tweaked with settings or that can be trained to a voice?

**Comment by sokorototo** [comment]
You can't access browser APIs from wasm and setting up a bridge is expensive. Plus what benefit does having a user speak to the app have?
