### ISSUE TITLE
goalParser inputs

### ISSUE THREAD

**Issue by JacobJax** [tijlleenders/ZinZen-scheduler#120]
Create `.txt` files for inputs parsed by goalParser

**Comment by tijlleenders** [comment]
@JacobJax 
We decided today to have the following types of tests in two repositories.

ZinZen repo:
- Cypress tests for the UI
- goalParser unit tests (text => tags)
- scheduler request tests (goals (including tags) => scheduler input)

ZinZen scheduler repo:
- scheduler input => scheduler output

@Tushar-4781 Right?

**Comment by Tushar-4781** [comment]
@tijlleenders yes. So technically @JacobJax you have to work on the last step cuz 1st step is done 2nd one will be done before next Friday meet

**Comment by JacobJax** [comment]
> @tijlleenders yes. So technically @JacobJax you have to work on the last step cuz 1st step is done 2nd one will be done before next Friday meet

On it.

**Comment by tijlleenders** [comment]
Tushar will implement this.

**Comment by tijlleenders** [comment]
Tushar will implement this.
