### ISSUE TITLE
Test wasm binary generated by new CI build process

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#122]
Test if the binary works okay in the front end.
The binary and associated files can be found in the `/pkg` directory of the `dev-build-front-end` branch.

**Comment by tijlleenders** [comment]
@egithinji Can we close this as obsolete?

We merged the new scheduler using the automated PR to main already.
https://github.com/tijlleenders/ZinZen/issues/684 has been made to look into why it is not showing any Tasks in the MyTime page.
