### ISSUE TITLE
Remove "builder pattern" methods from Goal struct

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#136]
The `Goal` struct (https://github.com/tijlleenders/ZinZen-scheduler/blob/main/src/goal.rs) currently contains a number of builder pattern methods (`duration`,`repeat`, etc). I think these were at some point used to construct goals.

However we're currently using deserialization via `Serde` to construct our `Goal` structs directly from json inputs, and so far so good. I haven't yet come across a place where I've needed to use the builder pattern to construct a Goal.

I propose we remove these methods from the `goal.rs` for now, for the sake of clarity and readability. Someone new to the codebase may spend time wondering what the purpose is for these methods.

**Comment by tijlleenders** [comment]
This issue can be generalized to solve all clippy warnings.

**Comment by egithinji** [comment]
There's a place in the unit tests where this builder pattern proved useful so might keep it after all. I'll close the issue for now...
