### ISSUE TITLE
Write tests for "x times a week"

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#148]
e.g. 
{
      "id": 1,
      "title": "exercise",
      "duration": 2,
      "repeat": "4/week"
}

e.g.
{
      "id": 1,
      "title": "write blog article",
      "duration": 2,
      "repeat": "2/week",
      "after_time": 19,
      "before_time": 22
}

**Comment by tijlleenders** [comment]
Yeah, good one - let's start with the basics :)
Would like to suggest writing it as "2/week" so that we stay consistent with the other "1-3/week" in #145

**Comment by egithinji** [comment]
Okay
