### ISSUE TITLE
Refactor to include a Slot struct

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#152]
While working on #150 , I realized there's a need for some refactoring. To start with, we can benefit from a `Slot` struct that will encapsulate some functionality relating to working with time slots.  Currently we're working directly with tuples of `(NaiveDateTime,NaiveDateTime)` and this is becoming trickier as we add more complex features to the scheduler.

The `Slot` struct will at its core represent a contiguous block of time, defined by a start NaiveDateTime, an end NaiveDateTime plus useful methods for working with time slots.

**Comment by tijlleenders** [comment]
Good idea!

First step would be to define a test suite for Slot arithmetic: addition and substraction.

Single slot minus another could yield 2 slots as a result.
