### ISSUE TITLE
task_placer not following algorithm

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#166]
@egithinji 
The task_placer currently loops through all tasks once to check if any have flexibility 1.
```
    for index in 0..tasks.len() {
        if tasks[index].flexibility == 1 {
            let my_slots = tasks[index].get_slots();
            tasks[index].set_confirmed_start(my_slots[0].start);
            tasks[index].set_confirmed_deadline(my_slots[0].end);
            tasks[index].status = SCHEDULED;
            //slide 10 (remove the assigned slot from other tasks' slot lists)
            remove_slots_from_tasks(&mut tasks, my_slots[0].start, my_slots[0].end);
        }
    }
```

However, this needs to be done after every time a Task is scheduled (TaskStatus::SCHEDULED).

I would suggest implementing a loop (with a loop protection/limit) that goes through all tasks to find an UNSCHEDULED task with flex 1.  
- If found and scheduled (including recalculating all flexibilities impacted) - restart the loop.
- If none UNSCHEDULED with flex 1 are found - pick the one with highest flex, schedule (including recalculating all flexibilities impacten) - restart the loop.
- If no UNSCHEDULED are left (or if loop limit is reached) - exit the loop

**Comment by egithinji** [comment]
So if I understand correctly, when a task is scheduled, we shouldn't just proceed with the remaining tasks in the loop. We need to schedule any tasks that now have flex 1, then loop again starting with highest flex downwards?

**Comment by tijlleenders** [comment]
Yes, after each Task that is scheduled the time slot used by the scheduled Task needs to be removed from any Tasks that (partly) had that slot in the possible slots. For those Tasks the flexibility needs to be recalculated. If the flexibility is recalculated this could result in Tasks getting flex 1 or 0 (problem) and the previously sorted order is no longer valid.
