### ISSUE TITLE
Regression on last scheduler release

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#201]
![image](https://user-images.githubusercontent.com/44887755/204877248-69723306-58a4-4640-901a-8fe493bf9a6c.png)

**Comment by tijlleenders** [comment]
@egithinji Can you fix this before continuing the work on new features?

**Comment by egithinji** [comment]
How come `start` and `deadline` for the goals are not date bounds (the time portion should be 00:00:00)?

**Comment by tijlleenders** [comment]
I guess we found the problem ;)

The scheduler should treat start and deadline as datetime. 

This is different from after/before in that it is not a daily thing - just the extremities constraint of the slot timelime. It can very well be combined with after/before or aome other conatraints.

**Comment by tijlleenders** [comment]
https://github.com/tijlleenders/ZinZen-scheduler/issues/163

**Comment by egithinji** [comment]
Alright will work on this next.

**Comment by egithinji** [comment]
Closed by #203
