### ISSUE TITLE
Add tests for "daytime"

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#205]
@tijlleenders What's the expected behavior for this? Will it be for e.g. "meditate 1hr daily daytime"?
i.e. daytime essentially replaces after_time/before_time with a default like 6am to 6pm?

**Comment by tijlleenders** [comment]
@Tushar-4781 I think what Eric suggests is the way to go for things like 'daytime/nighttime/morning/afternoon/evening'.

The actual times that correspond to this will at some point be a user preference - so it's logical to translate this on the frontend, not in the scheduler.

So UI would translate this into the right after/before tags.

Agree?
