### ISSUE TITLE
before_time combined with daily causes an error

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#219]
@egithinji 
Wasn't this resolved?
If so could you document how to pull the new version from the ZinZen repo?

![image](https://user-images.githubusercontent.com/44887755/212472600-6a60db25-59e6-430c-8e9c-a2dd1c25beea.png)

**Comment by tijlleenders** [comment]
"Daily" input with a capital D can't be parsed by scheduler.
@Tushar-4781 this can probably be solved by feeding the case sensitive scheduler a "daily" instead of "Daily".

**Comment by egithinji** [comment]
Yes all repetitions should be lower case. Did changing this fix the problem for you?

**Comment by tijlleenders** [comment]
Fixed by #945
