### ISSUE TITLE
Benchmark suite

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#22]
Benchmark the test case from #3 using Criterion as explained in https://youtu.be/eIB3Pd5LBkc

**Comment by tijlleenders** [comment]
Benchmarking isn't that simple.
There are multiple levels involved:  
- Compiled WASM
- The browser running JS + WASM API with translations back & forth

We are testing the WASM by converting the JSON test files in Rust tests. 
That could be benchmarked with Criterion - but not a prio for now.

We're using "deno bench" as a proxy for the browser end-to-end test (#36).

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
This could be interesting to try for the end-to-end performace on browser side: https://github.com/old-storyai/tracing-wasm

**Comment by moaz-mokhtar** [comment]
Ok I will figure out and feedback you
