### ISSUE TITLE
Documentation and clean code

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen-scheduler#220]
- Document the main modules and functions
- Remove unused code
- Clean code, reduce `clippy` warnings

**Comment by tijlleenders** [comment]
@egithinji Please document how to pull the latest version from the ZinZen repo and have someone test it based on the provided documentation.

**Comment by tijlleenders** [comment]
@egithinji We're documenting in the code right?
Should we get rid of the Wiki?

**Comment by tijlleenders** [comment]
Clippy warnings fixed by #225

**Comment by egithinji** [comment]
> @egithinji We're documenting in the code right? Should we get rid of the Wiki?

Yes in the code, but I'd also suggest we also have a pdf detailing the steps of the algorithm, and place it somewhere in the repo. Like the one I did a while back.
