### ISSUE TITLE
Group toast shows in wrong group

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#251]
When a group has no goals the below info message is not shown immediately.

It is delayed till you enter a group with goals/polls.

It should show immediately.![20230219_073115.jpg](https://user-images.githubusercontent.com/44887755/220030184-e58efe8a-9fe1-45d6-abe9-5d803f6d1547.jpg)

**Comment by tijlleenders** [comment]
@Tushar-4781 Sorry I put this issue in the wrong repo.

**Comment by Tushar-4781** [comment]
@tijlleenders  I can't reproduce any such error. Can u put a gif or a short video of the process and outcome

**Comment by tijlleenders** [comment]
Not reproducible.
