### ISSUE TITLE
Basic error handling

### ISSUE THREAD

**Issue by xy2iii** [tijlleenders/ZinZen-scheduler#26]
There's no error handling yet. The module will crash and do a console.error() of the `unwrap`. The old code had some error handling facilities that I ignored for getting the first test down, hopefully we can reuse this.

Instead of returning a Output, return a Result<Output> and report any errors to the user.
Also report errors with parsing the input via serde.

Apparently [wasm-bindgen can handle `Result<T>`s](https://rustwasm.github.io/docs/wasm-bindgen/reference/types/result.html), so hopefully we have no problems there.

**Comment by sokorototo** [comment]
Ok let me get to work on this

**Comment by sokorototo** [comment]
I will have to change the signatures of some functions to Result<T> from T

**Comment by sokorototo** [comment]
#30
