### ISSUE TITLE
Passing children with no duration is breaking the scheduler

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen-scheduler#265]
The scheduler should eliminate the goals that don't have the duration parameter. And in case if its a child of a goal that has no duration then its **id** has to be removed from the children array of the respective parent

**Comment by tijlleenders** [comment]
Scheduler can't schedule anything without a duration. For now we're filtering everything in the frontend. Later there might be some more complicated hierarchies where the child of a goal with duration doesn't have a duration, but its child has a duration.
Removing it then would 'break' the ancestor chain.

I'll mark it low prio as Tushar has quick fixed it for now in the frontend.
Scheduler will not get any goals without duration

We could make it a (option(min),option(max) tuple someday.

**Comment by tijlleenders** [comment]
Fixed by filtering on front-end https://github.com/tijlleenders/ZinZen/pull/1084
