### ISSUE TITLE
Remove "-filler" from goal id in output

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#274]
The output currently has a -filler suffix on the goal id:
![image](https://user-images.githubusercontent.com/44887755/227717939-2dc23bbf-65bb-42d0-b1e6-9d6cc210649b.png)

This needs to be removed as the UI doesn't handle it nicely.
Preference is to remove it in the algorithm, but if it is required to get good results then it needs to be removed in the output formatter.

**Comment by moaz-mokhtar** [comment]
Which test showing this result?

**Comment by moaz-mokhtar** [comment]
Issue resolved in PR https://github.com/tijlleenders/ZinZen-scheduler/pull/282

**Comment by tijlleenders** [comment]
> Issue resolved in PR #282
@moaz-mokhtar 
Tip: If you add "Resolves #issuenumber" in the PR description it will auto-close the issue on merge.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
