### ISSUE TITLE
Create test case if time filters for before and after is the same and handle issues

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#281]
While handling test case issue `every_2_hours_overlap`, found another case to recover which is if time filters are the same.
So need to create test case and handle if causing issues.

Sample: 
```json
{
  "startDate": "2022-11-01T00:00:00",
  "endDate": "2022-11-12T00:00:00",
  "goals": {
    "1": {
      "id": "1",
      "title": "study Rust",
      "min_duration": 1,
      "repeat": "every 2 hours",
      "filters": {
        "after_time": 07,
        "before_time": 07
      }
    }
  }
}
```

**Comment by tijlleenders** [comment]
This should be prevented by the frontend.
No need to make a test for this in the scheduler. In any case this would result in impossible as no time slot would be available.
