### ISSUE TITLE
Feature request: mixing daily and weekly budgets

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#287]
Feature to allow daily and weekly budgets.
```
As a user, I want set a goal with weekly budget and daily budget, so tasks have weekly and daily constraint
Example:
I want to to learn Rust with below constraints:
- minimum 20 hours weekly
- minimum 5 hours daily

So in this example, task can't be less than 5 hours daily and can't be less than 20 hours weekly.
```

**Comment by tijlleenders** [comment]
I would say maximu 5h daily... no?

**Comment by tijlleenders** [comment]
Mixing would have to be done by setting a daily budget as a subgoal of a weekly budget - as UI won't allow adding two budgets on a single goal right now.

**Comment by moaz-mokhtar** [comment]
My suggestion is to change the API to support many budgets. This will minimize complexity.
Check below sample:
```json
{
    "startDate": "2022-10-01T00:00:00",
    "endDate": "2022-11-01T00:00:00",
    "goals": {
        "1": {
            "id": "1",
            "title": "work",
            "budgets": [
                {
                    "budget_type": "Weekly",
                    "min": 35,
                    "max": 40
                },
                {
                    "budget_type": "Daily",
                    "min": 5,
                    "max": 10
                }
            ]
        }
    }
}
```

In case, priority to make it a `subgoal of weekly budget`, I think it may increase complexity which you have to set many properties like the parent goal.

So input for this case will be as below:
```json
{
    "startDate": "2022-10-01T00:00:00",
    "endDate": "2022-11-01T00:00:00",
    "goals": {
        "1": {
            "id": "1",
            "title": "work",
            "filters": {
                "after_time": 6,
                "before_time": 16
            },
            "budgets": [
                {
                    "budget_type": "Weekly",
                    "min": 35,
                    "max": 40
                }
            ],
            "children": [
                "2"
            ]
        },
        "2": {
            "id": "2",
            "title": "work-daily",
            "filters": {
                "after_time": 6,
                "before_time": 16
            },
            "budgets": [
                {
                    "budget_type": "Daily",
                    "min": 5,
                    "max": 10
                }
            ]
        }
    }
}
```

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
Good point and I like the proof by example!

Allowing multiple budgets could simplify the API, but it would then complicate the UI...
@Tushar-4781 What do you think? Simplicity in the UI should be favored over simplicity on the code.

A part from that I think there are valid use cases for having a daily budget within a weekly budget - so in any case that should be possible.
Let's say you have this work example and you want to spend max 2h per day on commute/meetings/something - then you still want to have the rest of the day to do actual work. If you combine the budgets in one goal this is not possible.

**Comment by tijlleenders** [comment]
I don't agree with below proposal, let's have a call today.

```
"children": [ { "goal_id": "2", "type": "sub-budget" } ]
```

**Comment by moaz-mokhtar** [comment]
I can suggest below for UI, so we will develop backend based on agreement.
![image](https://user-images.githubusercontent.com/5870208/230542609-a60c3a5c-5ced-4028-8c22-eb18a6998b9f.png)

---

Currently my design is as below:
`task_generator.rs`:
```rust
pub fn task_generator(
   ...
) -> TasksToPlace {
    let mut counter: usize = 0;
    let mut tasks: Vec<Task> = vec![];
    let mut goals: BTreeMap<String, Goal> =
        add_start_and_end_where_none(goals, calendar_start, calendar_end);
    
    validate_mixed_budgets(&mut goals);
    
    ...
}

fn validate_mixed_budgets(goals: &mut BTreeMap<String, Goal>) {
    /*  
    Todo 2023-04-07 | Issue 287
    Rules:
    - Only one children of type sub-budget
    - children goal not allowed to have childrens 
    - will consider only 3 fields for this type of children: [id, title, budgets]

    Algorithm:
    loop over goals:
        if goal have a childrens:
            PANIC if more than one children of type sub-budget
            let children = goal.children[type:SubBudget]
            PANIC if children have childrens
            process:
            - insert 
            - children goal

            

    */
}
```

--- 

For this design:
```json
"children": [ { "goal_id": "2", "type": "sub-budget" } ]
```

I preferred this, for efficiency.

So let is discuss.

**Comment by moaz-mokhtar** [comment]
Previous example not completed.
There is update regarding the proposed algorithm as below:
```
    Rules:
    - Only one children of type sub-budget
    - children goal not allowed to have childrens 
    - will consider only 3 fields for this type of children: [id, title, budgets]

    Algorithm:
    loop over goals:
        if goal have a childrens:
            PANIC if more than one children of type sub-budget
            let children = goal.children[type:SubBudget]
            PANIC if children have childrens
            process:
            - insert budget of children into goal.budgets
            - remove children from goals
            

```

In brief:
- we will add `budgets` of the subgoal which have daily budget into the parent goal internally
- will remove the subgoal for daily budget ` "budget_type": "Daily"`. 
- scheduling will be for parent goal only

**Comment by tijlleenders** [comment]
There are too many dimensions to this discussion. Let's have a call when ypu are available.

**Comment by tijlleenders** [comment]
You UI design could work - but what about min and max? 
Then we get four fields onstead of two. Could still work. @Tushar-4781 ?

**Comment by moaz-mokhtar** [comment]
Let is have a call

**Comment by tijlleenders** [comment]
Ok, so we agree that:
- it should be possible for a goal to have more than one budget; if you want to exercise 10h a week but max 2h day you shouldn't have to make a subgoal with the same name
- it should be possible to nest goals with budgets; for example you you have a weekly work budget, but then nested goals for different customers.
