### ISSUE TITLE
Doc request: JSON Input documentation

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#288]
Each time we develop features or enhancing system, there are changes to the JSON `Input` which contains goals information and it is the main entry object to the system.
```rust
pub struct Input {
    #[serde(rename = "startDate")]
    pub calendar_start: NaiveDateTime,
    #[serde(rename = "endDate")]
    pub calendar_end: NaiveDateTime,
    pub goals: BTreeMap<String, Goal>,
}
```
Sample of `input.json`:
```json
{
    "startDate": "2022-01-01T00:00:00",
    "endDate": "2022-01-02T00:00:00",
    "goals": {
      "1": {
        "id": "1",
        "title": "shopping",
        "min_duration": 1,
        "start": "2022-01-01T00:00:00",
        "deadline": "2022-01-02T00:00:00",
        "filters": {
          "after_time": 10,
          "before_time": 13
        }
      },
      "2": {
        "id": "2",
        "title": "dentist",
        "min_duration": 1,
        "start": "2022-01-01T00:00:00",
        "deadline": "2022-01-02T00:00:00",
        "filters": {
          "after_time": 10,
          "before_time": 11
        }
      },
      "3": {
        "id": "3",
        "title": "exercise",
        "min_duration": 1,
        "start": "2022-01-01T00:00:00",
        "deadline": "2022-01-02T00:00:00",
        "filters": {
          "after_time": 10,
          "before_time": 18
        }
      }
    }
  }
````

So I would like to suggest to create a documentation for below:
- Guide and support creating `input.json` 
- Showing available options and features to be used
- Support development and testing

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
Very good idea!

To my surprise I can't find an existing issue for API documentation.

Do you have a method in mind?

I propose we use some open standard/spec  but I don't think OpenAPI or JSONAPI are appropriate here as it is more of an internal interface spec...? What do you think?

Also, I don't think we should invest too much / go crazy on this -  as documentation is most useful for newcomers and we don't have that many at this point in the project. 

The value is in clearing our own thoughts and having a reference where frontend and wasm meet. A simple doc should do? Isn't that what the Rust interface spec does already?

**Comment by moaz-mokhtar** [comment]
My point of view we should have a doc at least for the `input.json` as below illustration:
- When we have a changes in the backend, the `input.json` format may be changed, so a documentation should be updated. 

**Example**
While I'm investigating https://github.com/tijlleenders/ZinZen-scheduler/issues/287,  I found that I may change the structure of data inside `input.json`  for `children` field as below example:
Before:
```json
{
    "startDate": "2022-10-01T00:00:00",
    "endDate": "2022-11-01T00:00:00",
    "goals": {
        "1": {
            "id": "1",
            "title": "work",
            "filters": {
                "after_time": 6,
                "before_time": 16
            },
            "budgets": [
                {
                    "budget_type": "Weekly",
                    "min": 35,
                    "max": 40
                }
            ],
            "children": [
                "2"
            ]
        },
        "2": {
            "id": "2",
            "title": "sub-budget",
            "budgets": [
                {
                    "budget_type": "Daily",
                    "min": 5,
                    "max": 10
                }
            ]
        }
    }
}
```

After update:
```json
{
    "startDate": "2022-10-01T00:00:00",
    "endDate": "2022-11-01T00:00:00",
    "goals": {
        "1": {
            "id": "1",
            "title": "work",
            "filters": {
                "after_time": 6,
                "before_time": 16
            },
            "budgets": [
                {
                    "budget_type": "Weekly",
                    "min": 35,
                    "max": 40
                }
            ],
            "children": [
                {
                    "goal_id": "2",
                    "type": "sub-budget"
                }
            ]
        },
        "2": {
            "id": "2",
            "title": "sub-budget",
            "budgets": [
                {
                    "budget_type": "Daily",
                    "min": 5,
                    "max": 10
                }
            ]
        }
    }
}
```

So updating doc, will minimize efforts for all participants, so they just check the doc that `children` changed.

- Another benefit is that not all of participants know all the fields of the `Goal` and how it is structured, so it will be very beneficial to have this kind of doc.

**Example**
```markdown
## Mandatory `input.json` fields
Any `input.json` must contains below fields:
- `startDate`: ....
- `endDate`: ....
- `goals`: contains list of goals. Each goal must have:...


{
    "startDate": "<START_DATE>",
    "endDate": "<END_DATE>",
    "goals": {
        "<GOAL_SERIAL>": {
            "id": "<GOAL_ID>",
            "title": "GOAL_TITLE"
        },
        ...
    }
}


```

--- 
Finally this is not a priority now, but should be in the plan when there is no priority tasks or when needed.

**Comment by moaz-mokhtar** [comment]
I would like to show a case which shows the importance of docs for the `input.json`.
For a test case called `flex-repeat-1`, I did face field `"repeat": "1-3/week"`, and also field ` "repeat": "3-5/week"` in another one, which I'm not sure about the functionality about it else by digging into the code.

```json
{
  "startDate": "2022-10-01T00:00:00",
  "endDate": "2022-11-01T00:00:00",
  "goals": {
    "1": {
      "id": "1",
      "title": "run 5km",
      "min_duration": 1,
      "repeat": "1-3/week"
    }
  }
}
```

**Comment by tijlleenders** [comment]
The input JSON is formalized in https://github.com/tijlleenders/ZinZen/issues/722
