### ISSUE TITLE
Feature request: change default scheduling to not splitting consequent slots

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#289]
When scheduling "Sleep 8h 21-6" the scheduler will schedule your sleep from 21-23 and 0-6, which is obviously not optimal.

We need a way to tell the scheduler not to split certain tasks while scheduling. This could be a do_not_split flag in the beginning - but could evolve to min_scheduled_duration - so probably call it that and set it to the min_duration in the test cases - and let ot default to 1h if not specified.

So a min_scheduled_duration of 8 will tell task_placer that it cannot schedule the task unless it is in a slot of 8 consecutive hours.

First idea for this approach:
- ~~always merge slots into one slot if they are adjacent ; this will for example be necessary after the filter pass which at least splits slots into days~~
- ~~remove time slots that cannot fit min_scheduled_duration before calculating flexibility~~

**Improved approach:**  
We first need to fix the fact that Slots are being split before being able to only schedule them if they fit entirely in one slot.
- Don't split slots at all. Keep the Timeline intact and only remove slots - so that no 'touching' slots can ever appear.
- When creating Tasks with `repeat` value, if beforetime < after time: change start of daily/weekly iteration to take few hours in previous day relative to calendar start. So "Sleep 22-8 daily" should start interating in 24h steps on the day before start of the calendar at 22:00, not 0:00.
- After this, we can add logic in the task_placer to default to not allow splitting - and only allow splitting if optional min_split_duration and/or max_split_duration input is present.

**Comment by moaz-mokhtar** [comment]
@tijlleenders Seeking your support for more info

**Comment by tijlleenders** [comment]
@moaz-mokhtar Updated description. Call me if you need further discussion.

**Comment by moaz-mokhtar** [comment]
I think this is should be the default behavior, and flag for the split. What is your opinion?

**Comment by tijlleenders** [comment]
Agree!

**Comment by moaz-mokhtar** [comment]
Seeking confirmation: 
- System by default will not split consequent tasks which have been split by date.
- This will be for kind of tasks

**Comment by tijlleenders** [comment]
Yeah agree that time slots of a task that are next to each other should be 'glued' into one bigger time slot.
That should probably take care of the problem.

**Comment by moaz-mokhtar** [comment]
This is initial `input.json` and `output.json` which expected the new functionality will proceed and output.

`input.json` :
```json
{
    "startDate": "2023-04-01T00:00:00",
    "endDate": "2023-04-08T00:00:00",
    "goals": {
        "1": {
            "id": "1",
            "title": "sleep",
            "min_duration": 8,
            "filters": {
                "after_time": 21,
                "before_time": 05
            }
        }
    }
}
```


`output.json` : 
```json
{
    "scheduled": [{
            "day": "2023-04-01",
            "outputs": [{
                    "taskid": 0,
                    "goalid": "free",
                    "title": "free",
                    "duration": 21,
                    "start": "2023-04-01T00:00:00",
                    "deadline": "2023-04-01T21:00:00"
                },
                {
                    "taskid": 1,
                    "goalid": "1",
                    "title": "sleep",
                    "duration": 8,
                    "start": "2023-04-01T21:00:00",
                    "deadline": "2023-04-02T05:00:00"
                }
            ]
        },
        {
            "day": "2023-04-02",
            "outputs": [{
                    "taskid": 2,
                    "goalid": "free",
                    "title": "free",
                    "duration": 16,
                    "start": "2023-04-02T05:00:00",
                    "deadline": "2023-04-02T21:00:00"
                },
                {
                    "taskid": 3,
                    "goalid": "1",
                    "title": "sleep",
                    "duration": 8,
                    "start": "2023-04-02T21:00:00",
                    "deadline": "2023-04-03T05:00:00"
                }
            ]
        },
        ...
    ],
    "impossible": [
        ...
    ]
}
```

**Comment by tijlleenders** [comment]
Was this test case ever failing?
I suggest you increase the flexibility as it is currently 1. Increase before from 5 to 8 for example.

**Comment by moaz-mokhtar** [comment]
As agreed that not-splitting will be by considering below:
- Avoid `splitting` into days or hours from iterators.
- Create a functionality to take care about remove slots from timeline, so iterator will not split the timeline.
- For goals like `sleep` consider in `Repeat` slots to avoid split a sleep slot into 2 because of midnight. Consider below algorithm: 
   - if beforetime < after time: change beforetime to take few hours  in previous day like (22 - 08)

**Comment by tijlleenders** [comment]
>if beforetime < after time: change start of daily/weekly iteration to take few hours in previous day like (22 - 08) relative to calendar start  

@moaz-mokhtar I think we can avoid having this custom business logic in the backend and move it to the front end. So whenever this is true the frontend will set the startdate time to after hours on the previous day of the regular startdatetime. Then the iteration logic will always just look at the start datetime and start iterating per 24h from there - whether it's at midnight or not.  

So to make it explicit - this would mean for the sleep-1 case the input would be this (notice the **):  
```
{
  "startDate": "2021-**12-31T22**:00:00",
  "endDate": "2022-01-09T00:00:00",
  "goals": {
    "1": {
      "id": "1",
      "title": "sleep",
      "min_duration": 8,
      "repeat": "daily",
      "filters": {
        "after_time": 22,
        "before_time": 6
      }
    }
  }
}
```
