### ISSUE TITLE
Add scheduler test

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#3]
Add a test to see verify that fixed appointments (with only one slot possible) get scheduled first... and the most flexible one stays out of the way.

 \>>date<< is the current date of the day the test is run.

**Input:**  
```
{
  goalId: 1,
  title : "shopping",  
  duration: 1,
  start: >>date<< 10:00 (ISO 8601),  
  deadline: >>date<< 13:00 (ISO 8601)
},   
{
  goalId: 2,  
  title: "dentist",  
  duration: 1,  
  start: >>date<< 10:00 (ISO 8601),
  deadline: >> date<< 11:00 (ISO 8601)  
},
{  
  goalId: 3,
  title : "exercise",  
  duration: 1,
  start: >>date<< 10:00 (ISO 8601),  
  deadline: >>date<< 18:00 (ISO 8601)
}  
```
**Expected result:**  

Summary version:  
Goal 1 => One task from 11-12  
Goal 2 => One task from 10-11   
Goal 3 => One task from 13-14  

Detailed version:  
```
pub struct Calendar {
    pub max_time_units: usize,
    pub time_unit_qualifier: String,
    pub tasks: Vec<Task>,  //Will have to discuss which Collection type is best suited
    pub slots: Vec<Slot>,  //Will have to discuss which Collection type is best suited
}
```

Where Vec\<Task> =
```
[  
  {
    task_id: x,
    duration_to_schedule: 0,
    duration_scheduled: 1,
    task_status: TaskStatus::Scheduled,
    goal_id: 1,
  },
  {
    task_id: y,
    duration_to_schedule: 0,
    duration_scheduled: 1,
    task_status: TaskStatus::Scheduled,
    goal_id: 2,
  },
  {
    task_id: z,
    duration_to_schedule: 0,
    duration_scheduled: 1,
    task_status: TaskStatus::Scheduled,
    goal_id: 3,
  },
]
```

and Vec\<Slot> =
```
[  
  {
    task_id: x,
    begin: 11,
    end: 2,
  },
  {
    task_id: y,
    begin: 10,
    end: 11,
  },
  {
    task_id: z,
    begin: 13,
    end: 14,
  },

```

**Comment by tijlleenders** [comment]
@sokorototo I apologize for not specifying this more clearly.  
It is not possible to just guess where I want to go with this.  

I've made the specification a little more detailed - but I'm sure I haven't thought of everything and questions will arise when implementing. Please contact me if anything is unclear.

**Comment by sokorototo** [comment]
Sure

**Comment by sokorototo** [comment]
Therefore input is expected to be:

```
{
  goalId: 1,
  title : "shopping",  
  duration: 1,
  start_constraint: >>date<< 10:00 (ISO 8601),
},   
{
  goalId: 2,  
  title: "dentist",  
  duration: 1,  
  start_constraint: >>date<< 13:00 (ISO 8601),
},
{  
  goalId: 3,
  title : "exercise",  
  duration: 1,
  start_constraint: >>date<< 16:00 (ISO 8601),
}  
```

**Comment by sokorototo** [comment]
This means that the tasks will take up all the time up to the next task's start time. Also tasks can take another tasks allocation if the flexibility allows it

**Comment by sokorototo** [comment]
An expected result would be
```rust
let tasks: Vec<Task> = vec![
  Task { goal_id: 1, start: >>date<< 10:00, finish: >>date<< 13:00, flexibility: 3 },
  Task { goal_id: 2, start: >>date<< 13:00, finish: >>date<< 16:00, flexibility: 3 },
  Task { goal_id: 1, start: >>date<< 16:00, finish: >>END OF SCHEDULE<<, flexibility: * },
];
```

**Comment by tijlleenders** [comment]
Please read the wiki - and stick to the documented structure of the Goal, Task, and Slot.

**Comment by tijlleenders** [comment]
**You wrote this expectation:**
> ```rust
> [
>   Task { goal_id: 1, start: >>date<< 10:00, finish: >>date<< 13:00, flexibility: 3 },
>   Task { goal_id: 2, start: >>date<< 13:00, finish: >>date<< 16:00, flexibility: 3 },
>   Task { goal_id: 1, start: >>date<< 16:00, finish: >>END OF SCHEDULE<<, flexibility: * },
> ];
> ```

**This is not the right expectation.**
The expected result after the preprocessor, and **before the core** processing would be this:
```
 tasks: Vec<Task> = vec![
  Task { id: 1, goal_id: 1, duration_to_schedule: 1, duration_scheduled: 0, task_status: TaskStatus::Unscheduled },
  Task { id: 2, goal_id: 2, duration_to_schedule: 1, duration_scheduled: 0, task_status: TaskStatus::Unscheduled },
  Task { id: 3, goal_id: 3, duration_to_schedule: 1, duration_scheduled: 0, task_status: TaskStatus::Unscheduled },
];
 slots: Vec<Slot> = vec![
  Slot { task_id: 1, begin: 10, end: 13 },
  Slot { task_id: 2, begin: 10, end: 11 },
  Slot { task_id: 3, begin: 10, end: 18 },
];
```

I would consider adding flexibility as an Option to the Task struct, as it is used heavily.
The flexibility would be 3, 1 and 8 respectively.

This is a relatively simple case.  
A Goal can have zero, one or many Tasks.  
A Task can have zero, one or many Slots.

**Comment by tijlleenders** [comment]
The flexibility will only be calculated when running the core - so after the preprocessor.
So when coming out of the preprocessor, the flexibilities will all be None.

We then calculate the flexibilities for each Task, giving us 3, 1, and 8.
Since any task with flexibility 1 has no other place to be scheduled, that Task (Task 2) gets scheduled from 10-11.
The other Slots for Task 1 and 3 now get 10-11 removed - since it is taken. 

NB: If another Slots starts before 10, and ends after 11, this would result in splitting a Slot into two new Slots.
But in this test case this does not happen as all Tasks start at 10.

Flexibility needs to be recalculated for all remaining unscheduled tasks.
Task 1 now has a Slot of 11-13, with a flexibility of 2.
Task 3 now has a Slot of 11-18, with a flexibility of 7.

Since there are no Tasks with a flexibility of 1, the Task with the highest flexibility gets chosen to be scheduled.
The first place in the Slot(s) for Task 3 that does not overlap with the Slot(s) for Task 1 is 13-14, so Task 3 gets scheduled there.
So the Slot for Task 3 is now 13-14 only and Task 3 has TaskStatus::Scheduled.

The remaining slots (only remaining is the Slot for Task 1) now get 13-14 removed.
The Slots for Task 1 are now only 11-13 so nothing gets removed.

Flexibility needs to be recalculated for all remaining unscheduled tasks.
Task 1 now has a Slot of 11-13, with a flexibility of 2.
The task with the highest flexibility gets chosed to be scheduled.

Now all Tasks are scheduled.

Task 2 with TaskStatus::Scheduled and one Slot from 10-11
Task 3 with TaskStatus::Scheduled and one Slot from 13-14
Task 1 with TaskStatus::Scheduled and one Slot from 11-12

**Comment by sokorototo** [comment]
Flexibility is calculated in the scheduler, alsoI found a way of avoiding a step. Meaning I never needed a Slot struct. Just the Goal and Task struct. Adding Slot to an implemented where it isn't used isn't looking promising.

**Comment by sokorototo** [comment]
Right now it uses displacement, so a task can displace another task. By the end of the iterations, we e end up with a very optimistic schedule

**Comment by tijlleenders** [comment]
Thia issue will be automatically vlosed when mentioned PR is merged.

**Comment by xy2iii** [comment]
#17
