### ISSUE TITLE
Don't generate dynamic tests from build.rs

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#306]
**Describe the bug**
Docs.rs build is failing to build.   
It is also annoying that the dynamic tests are in a different order after every build - it causes a lot of git diffs.  

**To Reproduce**
1. `cargo publish --dry-run`
4. See error :  
```
error: failed to verify package tarball  

Caused by:  
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.  
  Changed: /home/tijl/ZinZen-scheduler/target/package/zinzen-0.1.1/tests/rust_tests.rs  
```

**Expected behavior**
I can cargo publish without the build failing - and tests don't change if input doesn't change.  

**Solution**  
Let's keep generating the tests - but...:
- [x] make the order deterministic so it only changes minimally when new test cases are added.  
- [ ] Move dynamic tests generation out of the build script to `/src/bin/generate_rust_tests.rs`.   
We could have a 'shadow tests' directory with inputs and outputs so that any changes can easily be viewed in change control?
- [ ] In build.rs invoke `/src/bin/generate_rust_tests.rs` without writing to disk (using a no-write flag) - just compare with the one on disk and panic if there is a difference! This will catch it locally as well as during CI - but also allow publishing to docs.rs - as build.rs never writes outside of the OUTPUT_DIR.

**Alternate solution**  
- Put all the tests into one dynamic test. Not ideal for several reasons explained in links below.  
- Do some trickery with other crates mentioned in links below. Too complex compared to the 'good enough' solution proposed under 'Solution' header.  

**Context**
https://internals.rust-lang.org/t/pre-rfc-dynamic-tests/6790 and https://internals.rust-lang.org/t/dynamic-tests-revisited/18095

**Comment by moaz-mokhtar** [comment]
Check if issue minimized or resolved in PR: https://github.com/tijlleenders/ZinZen-scheduler/pull/307; I did force sort test directories so it will not be changed else if directories have changed.

I suggest below:
- no need to force this test at the beginning, so tests will be generated with a script manually
- make this test by `npm` only and let test in Rust as it going with PR https://github.com/tijlleenders/ZinZen-scheduler/pull/295

**Comment by tijlleenders** [comment]
> make this test by npm only  
@moaz-mokhtar The value of tests is higher when you do them closer to the code being modified. I prefer not to wait till we do a (slower) JS test or CI test. Agree or is there something I'm missing?

As outlined in PR #307 - the urgent work is done. Thanks. The rest is low prio.

**Comment by moaz-mokhtar** [comment]
Agreed to add below with priority in PR: https://github.com/tijlleenders/ZinZen-scheduler/pull/295 
- Each time test running, print out file `actual_output.json` for each test folder inside `tests/jsons`

**Comment by kobe-reygel** [comment]
@tijlleenders hi, I read the existing discussion on this.

I think I understand the proposed solution, but -if I'm not mistaken- this would mean that the tests are never actually generated and saved to disk locally, only when running.

This would not allow us to run individual testcases, which would IMO be kind of annoying.

What do you think of this proposed solution? https://github.com/tijlleenders/ZinZen-scheduler/pull/389

I introduced a feature to generate tests. I verified that cargo publish now works

This way we can enable the flag locally when we want to generate new tests (this only really needs to happen if we introduce new testcases, remove old ones or move them around in folders)




as far as version control annoyances go: I would only check in the actual test file jsons (possibly not even the observed, only input and expected). We don't need to check in the generated test code (and I even think it's already gitignored?)
