### ISSUE TITLE
A daily goal not scheduled properly on start of weekly repitition in test "flex-repeat-2"

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#311]
**Describe the bug**
While resolving issue in https://github.com/tijlleenders/ZinZen-scheduler/pull/295, specifically after resolving `Mon-Mon weekly repetition`; I found daily goal for `sleep` is not scheduled properly at the start of each weekly iteration.

So you will find task in 1st, 8th, 15th, 22nd, and 29th of October-2022, starting with goal `side project` instead of `sleep` like other days.

**Comment by tijlleenders** [comment]
@moaz-mokhtar I suspect this will be solved when #289 gets finalized.  
Blocked by #289

**Comment by tijlleenders** [comment]
Tests passing.
