### ISSUE TITLE
[BUG] Scheduler not marking rescheduled task impossible

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen-scheduler#312]
Update : issue description is in one of the last comments.

~~I'm trying to reschedule breakfast so initially scheduler assigned me 06:00 - 07:00 slot. When I tried to reschedule by providing that slot in not_on, It failed and still scheduling from 6-7. Below is the input~~
Update: removed input.

**Comment by moaz-mokhtar** [comment]
First very thankful @Tushar-4781  for this kind of tricky issues which I think this is healthy for the system on the long term.

After debugging I found below:
- No technical issues at all, check commit https://github.com/tijlleenders/ZinZen-scheduler/pull/295/commits/103196b87af01836c64e6dc1e8edaa4facd11495
- The `not_on` field in the mentioned `input.json` is not satisfying the `Input` standards which `not_on` must be inside `filters` not outside it.
- @tijlleenders I think, that will push to give a priority for issues like https://github.com/tijlleenders/ZinZen-scheduler/issues/299, https://github.com/tijlleenders/ZinZen-scheduler/issues/298, and https://github.com/tijlleenders/ZinZen-scheduler/issues/288, etc

**Comment by tijlleenders** [comment]
Nice to see the interaction to get this integrated!

@Tushar-4781 Can you confirm this solves your issue?  

@moaz-mokhtar Let's discuss 1:1 about next steps to smooth the integration with docs and/or error messages.

**Comment by Tushar-4781** [comment]
pardon me for re-opening this. here is a case
- I have to do breakfast (1h) between 6-9 (3h difference)
so if i reschedule 3 times consecutively, it doesn't show me the goal in impossible. as it should after rescheduling 3 times i gone out of my time bounds. so it should move to impossible right ?

Here is the input 

```
{
  "startDate": "2023-05-12T00:00:00",
  "endDate": "2023-05-19T00:00:00",
  "goals": {
    "b810f26f-d576-474e-be44-b0586168f95f": {
      "id": "b810f26f-d576-474e-be44-b0586168f95f",
      "title": "Me time 🧘🏽😌",
      "filters": {
        "after_time": 7,
        "before_time": 21,
        "not_on": [
          { "start": "2023-05-12T09:00:00", "end": "2023-05-12T10:00:00" }
        ]
      },
      "min_duration": 1,
      "repeat": "daily"
    },
    "b2709032-3e35-41b9-bfa1-01a43bb22ff8": {
      "id": "b2709032-3e35-41b9-bfa1-01a43bb22ff8",
      "title": "Breakfast 🥐🥣",
      "filters": {
        "after_time": 6,
        "before_time": 9,
        "not_on": [
          { "start": "2023-05-12T06:00:00", "end": "2023-05-12T07:00:00" },
          { "start": "2023-05-12T07:00:00", "end": "2023-05-12T08:00:00" },
          { "start": "2023-05-12T08:00:00", "end": "2023-05-12T09:00:00" }
        ]
      },
      "min_duration": 1,
      "repeat": "daily"
    },
    "737d0830-c7b0-4707-ad42-2b1c31617d88": {
      "id": "737d0830-c7b0-4707-ad42-2b1c31617d88",
      "title": "Walk 🚶🏽",
      "filters": { "after_time": 14, "before_time": 20 },
      "min_duration": 1,
      "repeat": "daily"
    },
    "571adecf-d1e8-4861-a323-a1cafa20f70d": {
      "id": "571adecf-d1e8-4861-a323-a1cafa20f70d",
      "title": "Lunch 🥪",
      "filters": { "after_time": 12, "before_time": 14 },
      "min_duration": 1,
      "repeat": "daily"
    },
    "4f030fa4-1897-4478-9f5f-f282f0d8f958": {
      "id": "4f030fa4-1897-4478-9f5f-f282f0d8f958",
      "title": "Sleep 😴🌙",
      "filters": { "after_time": 0, "before_time": 6 },
      "min_duration": 6,
      "repeat": "daily"
    },
    "25db3bf3-c6a4-49c3-af32-914aff107c92": {
      "id": "25db3bf3-c6a4-49c3-af32-914aff107c92",
      "title": "Dinner 🍽️",
      "filters": { "after_time": 18, "before_time": 21 },
      "min_duration": 1,
      "repeat": "daily"
    }
  }
}

```

**Comment by Tushar-4781** [comment]
@moaz-mokhtar @tijlleenders

**Comment by tijlleenders** [comment]
@Tushar-4781 I agree this is worth investigating. To be precise this is a new issue - but since there is not much history I'll just rename it.
