### ISSUE TITLE
Feature request: Statistics about my free/busy time for a time period

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#313]
**Is your feature request related to a problem? Please describe.**
One of the features which I think may provide a value to the user is informing him with basic statistics about free time which doesn't have any tasks and busy time with other useful info. So user will have insight about day/week/month utilization and similar.

**Comment by tijlleenders** [comment]
It makes sense to close #313 and include the free time statistics in #310.
