### ISSUE TITLE
fix function Task::remove_taken_slots

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#321]
**Describe the bug**
While fixing issue as per PR https://github.com/tijlleenders/ZinZen-scheduler/pull/320, found a calling to function which causing incorrect results. So need to fix this function and create test cases for that when needed or remove it if no need.

Function is: `Task::remove_taken_slots`.

Note: calling this function removed until resolving it, check commit https://github.com/tijlleenders/ZinZen-scheduler/pull/320/commits/1b29c2eff5bd791b82cea4776203333895894727

**Comment by tijlleenders** [comment]
No idea how to investigate this. Removing it.  
If there is any dead function left we will clean them up. Tests passing now.
