### ISSUE TITLE
test: create test cases for flex repeat feature

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#326]
As agreed before to remove all tests related to flex repeat like `"repeat": "3-5/week"` and similar which UI not implementing these features yet. 
We will create test for this feature again when we put it in a priority.
Check below references for more info.
PR: https://github.com/tijlleenders/ZinZen-scheduler/pull/325
Commit: https://github.com/tijlleenders/ZinZen-scheduler/commit/0e3bb0ed8f94281b3f0afe87a53603fe3a2ce601

**Comment by tijlleenders** [comment]
Abandoning flex repeat in favor of only using Budgets.
