### ISSUE TITLE
Proposal: business rule to make goal.min_duration for only daily periods

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#337]
**Is your feature request related to a problem? Please describe.**
It is related to Issue https://github.com/tijlleenders/ZinZen-scheduler/issues/318 and PR https://github.com/tijlleenders/ZinZen-scheduler/pull/327.

While I'm resolving PR https://github.com/tijlleenders/ZinZen-scheduler/pull/335, I found that it  sounds make sense to make below rules:
- Fields `Goal.min_duration` and `Goal.max_duration` are limited for daily limit ONLY.
- In case user asking for a limit for more period like week, month,etc,  like `work 40hrs/week`, so this must be set by fields `Goal.budgets.min`  and `Goal.budgets.max`.
- While creating `Step`s/`Task`s for budgeted `Goals`, we should enforce system to avoid setting field `Task.duration`/`Step.duration` to duration of long than one day periods.

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
I'm not sure I understand what this means. Are you talking about goals or steps?  
I think a goal of 50h for 'Project X' is perfectly reasonable. It will get divided into 50 stepa of 1h. Will I not be allowed to do this if we apply the rules mentioned in this issue?

What problem does this solve?  
Can you give a code example?

**Comment by moaz-mokhtar** [comment]
If user asking for 50hour for project x, so it should be:
```
Goal {
  Title: "project x"
  budgets: {min: 40 }
}

```

So we will solve misconception in the code to deferentiate if `min_duration` is for one week or one month or just one day.

In other means, we will make `Goal.min_duration` and `Goal.max_duration` means `minumim daily duration` and `maximum daily duration`.

**Comment by moaz-mokhtar** [comment]
I think this proposal near to the official documentation of the code.
```rust
pub struct Goal {
    ...
    /// The minimum duration per increment towards the Goal.
    #[serde(default)]
    pub min_duration: Option<usize>,
    
    /// The maximum duration, if the other Goals allow for it.
    #[serde(default)]
    pub max_duration: Option<usize>,
    ...
}

```
`Increment` is the `Step`; the new name of struct `Task`.

So that means if user asking for `project x for 40 hours`, it is wrong to set `min_duration: 40` and system should refuse it.


More examples to my idea:
```
// Below code is not accurate and trouble us in code
Goal {
  Title: "project x"
  min_duration: 40
}

// Below is correct
Goal {
  Title: "project x"
 budgets: { min: 40, type: weekly}
}

// if user set below, so he asking project 40 hours/ week and min 5 hours daily (per step)
Goal {
  Title: "project x"
  budgets: { min: 40, type: weekly}
  min_duration: 5
}



```

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
A 50h 'Project X' is not the same as a 50h/week budget. We shoukd not force people to use a budget per time period if that is not required.

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
The mentioned doc comment is wrong (my bad probably) when talking about min/max duration. When talking about min/max_duration increments should not be mentioned. If the goals needs a min/max per time period - that is a budget specification.

**Comment by tijlleenders** [comment]
@moaz-mokhtar  
And if we control over min/max per Step - we need to add extra parameters as this is currently controlled by the <=8h business rule. It is now either a block equal to min_duration or 1h blocks.  
Let's keep it that way for now to keep it simpler and avoid another min/max parameter.

**Comment by moaz-mokhtar** [comment]
Cool

**Comment by tijlleenders** [comment]
@moaz-mokhtar  
For Tasks (which exist only in output after introducing Steps) it is indeed impossible to have a duration longer than a day.

**Comment by moaz-mokhtar** [comment]
So I'm going to close this issue
