### ISSUE TITLE
Parse repetition "Mondays","Tues..." etc

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#34]
Repetition can be the name of a week day, "Mondays" to "Sundays".

The task_generator should generate a Task for each (part of a) corresponding day that is within the start and deadline timeline.

This issue starts with a test case that needs to be validated before implementing the code.
- [ ] Test case validated
- [ ] Implement

**Comment by egithinji** [comment]
This is now working and can be closed. If enhancements etc needed we can create other issues.
