### ISSUE TITLE
rename all output jsons

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#340]
**Describe the bug**
`output.json` feels like it is the observed output.  
`actual_output.json` is also ambiguous - is it what you actually expect? Maybe it's just me...

**Expected behavior**
Clear which output.json is expected and which one is observed.  
Rename `output.json` to `expected.json`.  
Rename `actual_output` to `observed.json`.

**Comment by moaz-mokhtar** [comment]
Good note, thanks for that

**Comment by moaz-mokhtar** [comment]
Resolved in PR: https://github.com/tijlleenders/ZinZen-scheduler/pull/344. Check commit: https://github.com/tijlleenders/ZinZen-scheduler/pull/344/commits/dc71f2a8d901b58fe5f9d887240078b68d245e46
