### ISSUE TITLE
rename repeat values that are actually filters

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#347]
**Describe the bug**
Repeat values like "Weekdays", "Mondays", "Weekends" are not actually repeat values - but a filter of "on_days" followed by a repeat every 24h (daily).

**Expected behavior**
Refactor all input files that use the 'old' repeat values.

**Comment by moaz-mokhtar** [comment]
Should I apply this in the `input.json` files only, or will be forced in internally  in the `Goal` struct.

```rust
pub struct Goal {
    ...

    pub repeat: Option<Repetition>,

    ...
}

pub enum Repetition {
    DAILY(usize),
    HOURLY,
    Weekly(usize),
    WEEKDAYS,
    WEEKENDS,
    EveryXdays(usize),
    EveryXhours(usize),
    MONDAYS,
    TUESDAYS,
    WEDNESDAYS,
    THURSDAYS,
    FRIDAYS,
    SATURDAYS,
    SUNDAYS,
    FlexDaily(usize, usize),
    FlexWeekly(usize, usize),
}
```

**Comment by tijlleenders** [comment]
Removing it in the struct will prevent it from being used - so good to do.

I would make that into a separate issue as it could impact other code internally.
