### ISSUE TITLE
output.json not formatted after running e2e test on new system

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#348]
**Describe the bug**  

When I run e2e tests on a new VSCode install with minimal config I get the following: 
![image](https://github.com/tijlleenders/ZinZen-scheduler/assets/44887755/b3b0a9bc-a0a1-4227-980d-b12b2b2a0824)

... when apparently we are expecting a formatting like this:
![image](https://github.com/tijlleenders/ZinZen-scheduler/assets/44887755/28f21ed4-529e-475e-b533-d19cefabbf3e)

Which one is it?  
How can we make it so that this is no longer VSCode env dependant?

**Comment by thinkrapido** [comment]
Solved with #411
