### ISSUE TITLE
Default e2e script without debug log

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#349]
**Describe the bug**
Running `./scripts/test e2e` to get actual_output.json files generates 300-400MB of logs.

**Expected behavior**
Only turn debug log on when running single test.

**Comment by moaz-mokhtar** [comment]
Resolved in PR https://github.com/tijlleenders/ZinZen-scheduler/pull/344. Check commit: https://github.com/tijlleenders/ZinZen-scheduler/pull/344/commits/9680fb35b3163263f0d50d919b254a580c802626
