### ISSUE TITLE
ref: rename module `splitters` to `transform`

### ISSUE THREAD

**Issue by moaz-mokhtar** [tijlleenders/ZinZen-scheduler#352]
**Describe the bug**
- Module `splitters` is not an accurate term.
- It does not actually split steps into smaller steps, it split goals into steps with timelines.
- After steps generation no splitting should occur.
- Module name `transform` is better and more convenient inside module `step_generator`.
- `goal => transform => steps`

**Comment by tijlleenders** [comment]
`Transform` is a worse name than `splitter` since it can literally mean anything as long as the output is different from the input.
