### ISSUE TITLE
fix goals_hierarchy

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#368]
**Describe the bug**
Update expectation and fix observed.  
Please note that filler goals don't get placed as long as:
- their flexibility is >1
- there are named 'siblings' - so named children of the same parent
This should happen even if the filler goal has a lower priority.

**Comment by kobe-reygel** [comment]
solved by https://github.com/tijlleenders/ZinZen-scheduler/pull/374
