### ISSUE TITLE
Change output format scheduler slots

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#37]
Right now the output of the scheduler slots is in this format:
```
      "slots": [
        {
          "task_id": 0,
          "start": 10,
          "end": 11,
        },
        {
          "task_id": 1,
          "start": 24,
          "end": 25,
        },
        {
          "task_id": 2,
          "start": 48,
          "end": 49,
        }
```

We would prefer a datetime format like "2022-01-01T10:00:00" instead of 10.

**Comment by tijlleenders** [comment]
@Tushar-4781 I think this is an ask from your side, right?
@egithinji We are still trying to find a format that is convenient for the Calender page UI to show the Tasks with.

**Comment by egithinji** [comment]
I'll look into this

**Comment by Tushar-4781** [comment]
@tijlleenders @egithinji 
input:  { goalid: number,
title: string,
duration: number,
start: String | date,
deadline: string | date }

sorted Output : { taskid: number, 
goalid: number,
title: string,
duration: number,
start: String | date,
deadline: string | date }[ ]

**Comment by tijlleenders** [comment]
Thanks.

Do we need the duration in the output since we know theae are slots on the calendar without flexibility?

**Comment by Tushar-4781** [comment]
> Thanks.
> 
> Do we need the duration in the output since we know theae are slots on the calendar without flexibility?

its Typescript if u remove that duration i have to create another interface for the output. so just to avoid extra work we can keep the schema the same.

**Comment by tijlleenders** [comment]
Ok, we'll pick it up when we have to.

**Comment by tijlleenders** [comment]
Sorry to come back on this.

All that is needed on TS/JS side is to change the output interface right?
Then let's do that instead of creating/sending/expecting extra values we don't need - and that we'll be confused about later.

**Comment by egithinji** [comment]
Hi could we agree on the type(s) of goals the app is expected to handle? I think this is important as this will inform the input format, output format, and logic of the scheduler.

Consider the following types of goals:
Type A: "Read a book, for 1 hour, daily, between 2000hrs and 2100hrs"
Type B: "Read a book, for 1 hour, daily, between 1st January 2022 and 31st January 2022"
Type C: "Read a book, for 1 hour, daily, between 1st January 2022 and 31st January 2022, between 2000hrs and 2100hrs"

The input currently specified is:
```input: {
goalid: number,
title: string,
duration: number,
start: String | date,
deadline: string | date
}```

This is fine, but we need clarity on what the "start" and "deadline" refer to.

If our goals are of Type A, then I assume "start" and "deadline" would be referring to the "2000hrs/2100hrs".

If our goals are of Type B, then I assume "start" and "deadline" would be referring to the "1st January 2022/31st January 2022".

If our goals are of Type C, then we are missing one set of parameters. The "start" and "deadline" can either refer to "2000hrs/2100hrs" or to "1st January 2022/31st January 2022".

And the logic implemented in the scheduler is affected by types of goals we're working with.

@Tushar-4781 and @tijlleenders is it possible to get some clarity on this?

**Comment by Tushar-4781** [comment]
@tijlleenders as per previous discussion on goal parser, we are only allowing time ( that too in hours ) not date as an input while addingGoal. so @egithinji type B & type C not in the picture. @tijlleenders plz confirm

**Comment by egithinji** [comment]
Thanks @Tushar-4781

**Comment by egithinji** [comment]
I believe the current repetitive deno test needs to now be adjusted to conform to the agreed upon output format. The current version is here: https://github.com/tijlleenders/ZinZen-scheduler/blob/main/js-tests/repetition.ts
I'm proposing adjusting the output part to the following (which I'll use in the rust end-to-end test):
```[
      {
        "taskid": 10,
        "goalid": 1,
        "title": "walk",
        "duration": 1,
        "start": "2022-01-01T00:00:00",
        "deadline": "2022-01-01T01:00:00",
      },
      {
        "taskid": 11,
        "goalid": 1,
        "title": "walk",
        "duration": 1,
        "start": "2022-01-02T00:00:00",
        "deadline": "2022-01-02T01:00:00",
      },
      {
        "taskid": 12,
        "goalid": 1,
        "title": "walk",
        "duration": 1,
        "start": "2022-01-03T00:00:00",
        "deadline": "2022-03-03T01:00:00",
      },
    ]```

@tijlleenders , @Tushar-4781 I believe we're all in agreement?

**Comment by tijlleenders** [comment]
@Tushar-4781 @egithinji This issue can be closed, right?
Where are we documenting the current output format?
