### ISSUE TITLE
Schedule filler steps last

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#381]
**Is your feature request related to a problem? Please describe.**
If I have concrete things like 'write report' I don't want that to be scheduled after a bunch of generic 'work' filler goals - that typically have a higher flex as they can be split into 1h steps.

**Describe the solution you'd like**
Update next step to be scheduled selection to take this into account.

**Describe alternatives you've considered**
None.

**Additional context**
Issue surfaced during #380 test case demo-2-with-filler-with-budget

**Comment by kobe-reygel** [comment]
As discussed in meeting, this seems to be already okay: the ordering of steps makes sure that filler steps are scheduled last.
@tijlleenders do you feel that this is sufficiently covered with the existing excel testcases? Or do we want to write an extra testcase just for this?

**Comment by tijlleenders** [comment]
This is covered.
