### ISSUE TITLE
Enable error hook wasm

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#384]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I get an incomprehensible error message on the UI side.

**Describe the solution you'd like**
Implement https://crates.io/crates/console_error_panic_hook 
It's already imported in cargo.toml - just not activated.

**Describe alternatives you've considered**
None

**Additional context**
The current wasm release is still giving errors when imported to the UI - even when the same input in the Rust binary passes the test.

**Comment by tijlleenders** [comment]
@kobe-reygel It would be great if you can pick this one first!

**Comment by kobe-reygel** [comment]
@tijlleenders on it

**Comment by kobe-reygel** [comment]
`The current wasm release is still giving errors when imported to the UI - even when the same input in the Rust binary passes the test.`

@tijlleenders I read over this the first time. That is very weird, especially since we have the passing deno tests... Could you send the offending input on to me?

**Comment by tijlleenders** [comment]
@kobe-reygel 
Actually I think it's something with the CI build that uses wasm-pack (which uses wasm-bingen under the covers). 

I manually built a wasm-bindgen release with target web and typescript bindings and that works... so it's not the Rust code.

**Comment by kobe-reygel** [comment]
<img width="521" alt="Screenshot 2023-09-14 at 21 35 02" src="https://github.com/tijlleenders/ZinZen-scheduler/assets/26096059/84df5794-7f8a-430b-84f7-00f7140e703d">

situation after https://github.com/tijlleenders/ZinZen-scheduler/pull/387  :)
