### ISSUE TITLE
deal with budgets that are filtered on days

### ISSUE THREAD

**Issue by kobe-reygel** [tijlleenders/ZinZen-scheduler#412]
**Is your feature request related to a problem? Please describe.**
The scheduler does not take filtering on days into account with step generation to reach a (minimum) budget.
e.g. a budget of 2 hours per day, but filtered on Wednesday still generates 2 hours for each day.

This has deep consequences for the way budgets are handled. 

**Describe the solution you'd like**
Think out a way we want the scheduler to deal with this type of constraint and implement it

**Additional context**
There is alreay a test file in the validated folder: budget-2-2-2-2. 
This is a special case where there is a weekly and a daily budget, both only on Wednesday and both _exactly_ 2 hours.

**Comment by tijlleenders** [comment]
Closing this as no reply from @kobe-reygel - please reopen if necessary.
