### ISSUE TITLE
naming conventions for development on branches

### ISSUE THREAD

**Issue by thinkrapido** [tijlleenders/ZinZen-scheduler#413]
I'd like to suggest a naming convention for branches we are working on.

[developer shortcut]/[issue number]/[meaningful name]

like: rom/411/new-scheduler

The branches should only be developed by the distinct developer and not mixed up.
This helps retrace the development train of each developer and does not get confusing.

Finished branches should be merged into the main branch after reviewing the pull request and then deleted.

If someone likes work on a branch of another developer, then branch from this one with the above naming convetion.

**Comment by tijlleenders** [comment]
Good proposal.  

We can already start working this way ... but let's close this issue once we document the decision on the tech docs?

**Comment by kobe-reygel** [comment]
nice proposal! I'll take this into account
