### ISSUE TITLE
Protect Step Timeline/Slots from direct manipulation

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#418]
**Is your feature request related to a problem? Please describe.**
@thinkrapido made me realize with the new scheduler approach that the interior state of Steps is directly manipulated. This complicates reasoning about the code and violates the open-closed principle.

**Describe the solution you'd like**
Give Steps a read-only ref to PlacedSteps so that a Step in StepsToPlace:
- can update it's own Timeline by watching what is being placed (so remove any Slots from its own Timeline that can't be used anymore because some other Step got placed there).
- can calculate and maintain/update its own Flexibility score.
- does not have its Timeline/Slots manipulated from the outside.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tijlleenders** [comment]
@kobe-reygel @thinkrapido  Does this make sense?

**Comment by kobe-reygel** [comment]
This makes sense, and this would be a massive ergonomic improvement.

This is a pervasive problem in multiple structs. (E.g. also for the goals struct in the preprocessing step)

So this is a great first step, and if this works out we can also look for other places in the code where this should happen 😄

**Comment by thinkrapido** [comment]
In general, my approach uses heavily references but can be further improved.

one comment on this issues description. It is difficult to read for me, but I think that newcomers don’t understand even less of the used notions. (A format would be good like telling it to a 5 year old :) )

**Comment by tijlleenders** [comment]
Resolved by implementing #411
