### ISSUE TITLE
I don't like the Goal Struct and its aggregations

### ISSUE THREAD

**Issue by thinkrapido** [tijlleenders/ZinZen-scheduler#419]
There should be clear and purposeful naming conventions and the elimination of code bloat.

**Is your feature request related to a problem? Please describe.**
I think that the Goal struct has fields which don't contribute much to the outcome and is cluttered and also redundant.

It seems, that it has evolved over time by the different participant and has been bloated with elements that we don't need in the first place.

There is a lack of convenience functions to get appropriate default data, like the nested filters fields.

**Describe the solution you'd like**
- we should get rid of budget and tags, because repetition does the thing
- the {min, max}_duration, start, and deadline is also misleading
- rethink filters - the name filters indicate an arbitrary number of filters, but effectively there is only one

**Comment by tijlleenders** [comment]
I agree the Goal struct has been bloated by different contributors.  
> we should get rid of budget and tags, because repetition does the thing. 
- I agree on getting rid of the Tags.
- I disagree on removing Budget. Budget is a core concept. In the UI we can add a Budget or a Goal node to the DAG. Removing it is like amputating a limb.  

> the {min, max}_duration, start, and deadline is also misleading. 
- Agree we can simplify {min, max}_duration to simply duration
- disagree on removing start/deadline - these are essential fields that have a counterpart in the UI.

>r ethink filters - the name filters indicate an arbitrary number of filters, but effectively there is only one.  
- there are multiple filters - at least for Budget nodes there is after/before, on_days, not_on

**Comment by thinkrapido** [comment]
Let's concider #424 and close this issue, if no further comments are given.

**Comment by tijlleenders** [comment]
@thinkrapido 
After our discussion on Budgets, a lot of the things disturbing you in the Goal struct have been stripped, and moved to Budget.  
I think that solves this issue - but feel free to disagree.
