### ISSUE TITLE
index out of bounds on tests (new input format)

### ISSUE THREAD

**Issue by kobe-reygel** [tijlleenders/ZinZen-scheduler#422]
**Describe the bug**
We get the following error:
index out of bounds: the len is 0 but the index is 0
thread 'e2e::a_test_see_below' panicked at src/services/placer/mod.rs:25:46:
index out of bounds: the len is 0 but the index is 0

**To Reproduce**

run one of following testcases:
weekly_2
sleep_1
budget_wednesday_2_2_2_2
budget_0_24_35_40

**Expected behavior**
the tests run green :)

**Additional context**
It may have to do with the fact that there is a new json format (see comments in https://github.com/tijlleenders/ZinZen-scheduler/pull/410#issue-1977802625 ) validate this

**Comment by tijlleenders** [comment]
@kobe-reygel I guess this issue is irrelevent when switching to the new-scheduler approach?

**Comment by thinkrapido** [comment]
Let's concider #424 and close this issue, if no further comments are given.

**Comment by tijlleenders** [comment]
Closing this as no reply from @kobe-reygel - please reopen if necessary.
