### ISSUE TITLE
Takling next steps after #411 - new scheduler

### ISSUE THREAD

**Issue by thinkrapido** [tijlleenders/ZinZen-scheduler#424]
- [ ] We should analyze carefully what test cases should be moved into the active bunch, proof manually, if the are valid, and enhance the scheduler according to these cases.

- [x] We need to remove much more dead code, that is left from the old scheduler.

- [x] We should optimize the code for better readability in general and move models to old_models before get rid of them. Accordingly, the new_models should then be renamed to models.

- [ ] We should enhance the new goal structure by all the necessary stuff, like repititions and daily filters. And also define the general time horizion for an calender 3months, 1, or 2 years, so we can map all of the events to prospect the schedule of the user properly if, for instance, yearly repetitions are active.  
Tijl: How about we keep it simple and just do a rolling forecast for 14 days in the future. This also saves a lot of manual calculation work for test cases.

- [ ] Integrate budgets, later on. (For me this concept isn't quite clear yet.) 
Tijl: Currently all the default goals that you get when first opening the app are budgets ... so it's crucial to grasp this concept and integrate it to the scheduler logic as soon as possible.

optional:
- [ ] Tree-like structure of goals as input for the scheduler. (This is also a FE issue and needs to be handled with care.)

**Comment by tijlleenders** [comment]
I'd say removing the old scheduler is the first thing to do. Clear the dead wood so we can see clearly - and move freely.  
After that I'd like to see support for some more test cases - as well as integrating budgets as soon as possible - as this is a core concept.

**Comment by thinkrapido** [comment]
"Integrate budgets ..."
Will be tackled next, now that I spoken to Tijl and we modeled the Budget and Goal structs.
We will also apply the TDD approach
to be continued...
