### ISSUE TITLE
Allow all Input fields to be optional except duration & Title of Goal 

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen-scheduler#71]

**Comment by egithinji** [comment]
@Tushar-4781 Currently the scheduler allows all fields except the following to be optional in the input json: id, title, and duration.
Is this what you mean or do you mean something else?

**Comment by Tushar-4781** [comment]
@egithinji yes, as per our last discussion, we want the scheduler to handle the input where it should allow all Input fields to be optional except duration & Title of Goal. The previous build I got 2 weeks back was not handling the above scenario. so if its done close this issue I will get the new build of the scheduler.

**Comment by egithinji** [comment]
@Tushar-4781 Okay. Yes if that's the case I believe the scheduler currently does what you describe.
The only thing that hasn't been merged yet is the renaming of the `repetition` field to `repeat`. @tijlleenders I've submitted PR for this, just awaiting you review and merge.

**Comment by tijlleenders** [comment]
Merged!

**Comment by egithinji** [comment]
Thanks. Then I guess I'll close the issue.
