### ISSUE TITLE
Remove unused libs from Cargo.toml

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen-scheduler#72]
```
linked-list = "0.0.3"
anyhow = "1.0.58"
```
Seem not to be used?

Also - not sure if ```console_error_panic_hook``` is necessary.

**Comment by egithinji** [comment]
Yes linked-list and anyhow not being used. I'll remove.
Haven't used `console_error_panic_hook` yet but might it be useful for debugging in near future? https://github.com/rustwasm/console_error_panic_hook

**Comment by tijlleenders** [comment]
Closed by #74
